//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int Id { get; set; }
        public int IdFactura { get; set; }
        public int Idproducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Itbis { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
