//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class existencia
    {
        public int Id { get; set; }
        public int IdProveedor { get; set; }
        public int IdProducto2 { get; set; }
        public string Documento { get; set; }
        public int ctd_entrada { get; set; }
        public int ctd_salida { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Existencia1 { get; set; }
        public System.DateTime Fecha_vent { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
